'use client';

import React, { useState } from 'react';
import { AuditRecord } from '@/lib/firebaseAdmin';
import { formatRupeesToINR } from '@/lib/financeUtils';
import {
  X,
  CheckCircle2,
  ShieldAlert,
  AlertTriangle,
  ArrowRight,
  UserCheck,
  UserX,
  Mail,
  Cpu,
  Sparkles,
  Lock,
  Calculator,
  Layers,
  Copy,
  Check,
  FileCheck2,
  SlidersHorizontal,
  Clock
} from 'lucide-react';

interface TransactionEvidenceDrawerProps {
  record: AuditRecord | null;
  onClose: () => void;
  onResolveAction?: (
    txnId: string,
    action: 'RESOLVE_MATCHED' | 'RESOLVE_UNMATCHED' | 'ACCEPT' | 'OVERRIDE' | 'RESOLVE' | 'ESCALATE' | 'REJECT',
    reviewer: string,
    reason: string,
    note?: string
  ) => Promise<void>;
}

export const TransactionEvidenceDrawer: React.FC<TransactionEvidenceDrawerProps> = ({
  record,
  onClose,
  onResolveAction,
}) => {
  const [reviewerName, setReviewerName] = useState('Finance Controller');
  const [opsEmail, setOpsEmail] = useState('ops-finance@company.com');
  const [note, setNote] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [actionSuccessMsg, setActionSuccessMsg] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  React.useEffect(() => {
    setActionSuccessMsg(null);
  }, [record?.txn_id]);

  if (!record) return null;

  const diffRupees = Math.abs(record.internal_amount - record.bank_amount);
  const score = record.confidence_score;
  const isFailClosed =
    record.policyAuth?.decision === 'REFUSED_FAIL_CLOSED' ||
    (record.status === 'FLAGGED_EXCEPTION' && !!record.policyAuth?.refusalReason);

  const handleCopy = (idText: string) => {
    navigator.clipboard.writeText(idText);
    setCopiedId(idText);
    setTimeout(() => setCopiedId(null), 1500);
  };

  const handleAction = async (
    action: 'RESOLVE_MATCHED' | 'RESOLVE_UNMATCHED' | 'ACCEPT' | 'OVERRIDE' | 'RESOLVE' | 'ESCALATE' | 'REJECT'
  ) => {
    if (!onResolveAction) return;
    setIsSubmitting(true);
    setActionSuccessMsg(null);
    try {
      if (action === 'ESCALATE') {
        const subject = `[ESCALATION] Reconciliation Exception: ${record.txn_id}`;
        const body = `Reconciliation Exception Escalation Report
----------------------------------------
Transaction ID: ${record.txn_id}
Razorpay Payment ID: ${record.razorpay_payment_id || record.txn_id}
Razorpay Settlement ID: ${record.razorpay_settlement_id || 'PENDING'}
Ledger Amount: ₹${formatRupeesToINR(record.internal_amount)} (${record.internal_date})
Bank Amount: ₹${formatRupeesToINR(record.bank_amount)} (${record.bank_date})
Variance / Diff: ₹${formatRupeesToINR(diffRupees)}
Payment Method: ${record.payment_method}
Policy Decision: ${record.policyAuth?.decision || 'REFUSED'}
Refusal Reason: ${record.policyAuth?.refusalReason || 'None'}
Explanation: ${record.explanation}

Reviewer: ${reviewerName}
Audit Note: ${note || 'Escalated for manual ops investigation'}
----------------------------------------
Generated by Nexus Reconcile Finance Controller`;

        const mailtoUrl = `mailto:${encodeURIComponent(opsEmail)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
        window.open(mailtoUrl, '_blank');
      }

      await onResolveAction(record.txn_id, action, reviewerName, `Controller manual action: ${action}`, note);

      let successText = '';
      if (action === 'ESCALATE') {
        successText = `Transaction ${record.txn_id} escalated to Ops & email client launched!`;
      } else if (action === 'RESOLVE_MATCHED' || action === 'ACCEPT' || action === 'OVERRIDE') {
        successText = `✓ Transaction ${record.txn_id} marked as Human Resolved: Matched by ${reviewerName}!`;
      } else if (action === 'RESOLVE_UNMATCHED' || action === 'REJECT') {
        successText = `✕ Transaction ${record.txn_id} marked as Human Resolved: Not Matched by ${reviewerName}!`;
      } else {
        successText = `Transaction ${record.txn_id} resolution logged!`;
      }

      setActionSuccessMsg(successText);
      setTimeout(() => {
        onClose();
      }, 1200);
    } catch (e) {
      console.error('Error logging controller action:', e);
    } finally {
      setIsSubmitting(false);
    }
  };

  // Fallback math values if mathJourney is not yet populated on older records
  const math = record.mathJourney || {
    ledgerGrossRupees: record.internal_amount,
    mdrRatePct: 2.0,
    mdrRupees: Math.round(record.internal_amount * 0.02 * 100) / 100,
    gstRatePct: 18.0,
    gstRupees: Math.round(record.internal_amount * 0.02 * 0.18 * 100) / 100,
    netExpectedRupees: Math.round((record.internal_amount - record.internal_amount * 0.02 * 1.18) * 100) / 100,
    actualBankRupees: record.bank_amount,
    varianceRupees: diffRupees,
    formulaString: `Ledger ₹${formatRupeesToINR(record.internal_amount)} - 2.0% MDR - 18% GST = Net Expected`,
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/75 backdrop-blur-sm flex justify-end">
      <div className="w-full max-w-2xl bg-white dark:bg-[#0E1524] h-full shadow-2xl overflow-y-auto flex flex-col justify-between border-l border-slate-200 dark:border-slate-800 animate-in slide-in-from-right duration-200">
        
        {/* Drawer Header */}
        <div>
          <div className="p-6 border-b border-slate-200 dark:border-slate-800 bg-slate-50/80 dark:bg-[#131B2A]/90 sticky top-0 z-10 backdrop-blur">
            <div className="flex items-start justify-between">
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-mono font-extrabold text-lg text-slate-900 dark:text-white flex items-center gap-1.5">
                    {record.txn_id}
                  </span>
                  <button
                    onClick={() => handleCopy(record.txn_id)}
                    className="p-1 rounded text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-200 dark:hover:bg-slate-800 transition"
                    title="Copy Transaction ID"
                  >
                    {copiedId === record.txn_id ? (
                      <Check className="w-3.5 h-3.5 text-emerald-500" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                  </button>

                  <span
                    className={`px-2.5 py-0.5 rounded-full text-xs font-bold font-mono ${
                      score >= 90
                        ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20'
                        : score >= 70
                        ? 'bg-amber-500/10 text-amber-500 border border-amber-500/20'
                        : 'bg-rose-500/10 text-rose-500 border border-rose-500/20'
                    }`}
                  >
                    Confidence: {score}%
                  </span>

                  {/* Policy Decision Pill */}
                  {record.policyAuth?.decision === 'AUTHORIZED' ? (
                    <span className="px-2 py-0.5 rounded text-[11px] font-bold font-mono bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
                      <CheckCircle2 className="w-3 h-3" />
                      <span>AUTHORIZED</span>
                    </span>
                  ) : (
                    <span className="px-2 py-0.5 rounded text-[11px] font-bold font-mono bg-rose-500/15 text-rose-600 dark:text-rose-400 border border-rose-500/30 flex items-center gap-1">
                      <Lock className="w-3 h-3" />
                      <span>FAIL-CLOSED REFUSAL</span>
                    </span>
                  )}
                </div>

                {/* Razorpay Entity Nomenclature Subtitle */}
                <div className="flex flex-wrap items-center gap-2 mt-2 text-xs font-mono text-slate-500 dark:text-slate-400">
                  <span className="bg-slate-200/60 dark:bg-slate-800/80 px-2 py-0.5 rounded text-[11px]">
                    Pay: {record.razorpay_payment_id || record.txn_id}
                  </span>
                  {record.razorpay_settlement_id && (
                    <span className="bg-slate-200/60 dark:bg-slate-800/80 px-2 py-0.5 rounded text-[11px]">
                      Setl: {record.razorpay_settlement_id}
                    </span>
                  )}
                  <span className="bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20 px-2 py-0.5 rounded text-[11px]">
                    Webhook: {record.razorpay_event || 'settlement.processed'}
                  </span>
                </div>
              </div>

              <button
                onClick={onClose}
                className="p-2 rounded-xl text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-800 transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* 3-Step Visual Journey Stepper */}
            <div className="mt-5 pt-4 border-t border-slate-200/70 dark:border-slate-800/70">
              <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">
                Reconciliation Audit Trail (Evidence &rarr; Candidates &rarr; Policy)
              </div>
              <div className="grid grid-cols-3 gap-2">
                {/* Step 1 */}
                <div className="p-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex items-center space-x-2">
                  <div className="w-6 h-6 rounded-full bg-blue-500/10 text-blue-600 dark:text-blue-400 flex items-center justify-center font-mono font-bold text-xs">
                    1
                  </div>
                  <div className="min-w-0">
                    <p className="text-[11px] font-bold text-slate-900 dark:text-white truncate">Input Evidence</p>
                    <p className="text-[9px] text-slate-500 truncate">Normalized & Extracted</p>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="p-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex items-center space-x-2">
                  <div className="w-6 h-6 rounded-full bg-purple-500/10 text-purple-600 dark:text-purple-400 flex items-center justify-center font-mono font-bold text-xs">
                    2
                  </div>
                  <div className="min-w-0">
                    <p className="text-[11px] font-bold text-slate-900 dark:text-white truncate">Candidates</p>
                    <p className="text-[9px] text-slate-500 truncate">
                      {record.candidatesEvaluated?.length || 1} Evaluated
                    </p>
                  </div>
                </div>

                {/* Step 3 */}
                <div
                  className={`p-2.5 rounded-lg border flex items-center space-x-2 ${
                    isFailClosed
                      ? 'bg-rose-500/10 border-rose-500/30'
                      : 'bg-emerald-500/10 border-emerald-500/30'
                  }`}
                >
                  <div
                    className={`w-6 h-6 rounded-full flex items-center justify-center font-mono font-bold text-xs ${
                      isFailClosed
                        ? 'bg-rose-500/20 text-rose-500'
                        : 'bg-emerald-500/20 text-emerald-500'
                    }`}
                  >
                    3
                  </div>
                  <div className="min-w-0">
                    <p
                      className={`text-[11px] font-bold truncate ${
                        isFailClosed ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'
                      }`}
                    >
                      {isFailClosed ? 'Policy Refusal' : 'Policy Authorized'}
                    </p>
                    <p className="text-[9px] text-slate-500 truncate">Deterministic Rules</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="p-6 space-y-6">

            {/* FAIL-CLOSED REFUSAL ALERT BANNER (DIRECTIVE 1: REWARD THE REFUSAL) */}
            {isFailClosed && (
              <div className="p-4 rounded-xl bg-rose-500/10 dark:bg-rose-950/30 border-2 border-rose-500/40 text-rose-900 dark:text-rose-200 space-y-2">
                <div className="flex items-center space-x-2 text-rose-600 dark:text-rose-400 font-extrabold text-sm">
                  <ShieldAlert className="w-5 h-5 flex-shrink-0 animate-pulse text-rose-500" />
                  <span>POLICY ENFORCEMENT: REFUSED AUTO-RESOLUTION</span>
                </div>
                <div className="font-mono text-xs font-bold bg-rose-500/20 px-3 py-2 rounded-lg text-rose-800 dark:text-rose-200 border border-rose-500/30">
                  {record.policyAuth?.refusalReason || 'Confidence insufficient. Multiple plausible candidates. DO NOT AUTO-RESOLVE.'}
                </div>
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] text-rose-700 dark:text-rose-300 font-mono">
                  <span>Rule: {record.policyAuth?.policyRule || 'POLICY_FAIL_CLOSED'}</span>
                  <span>•</span>
                  <span>Authorized By: Deterministic Policy Engine</span>
                  <span>•</span>
                  <span>Status: Fail-Closed Enforced</span>
                </div>
              </div>
            )}

            {/* Amount Comparison Cards */}
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                <span className="text-[10px] text-slate-400 font-semibold uppercase block mb-1">Ledger Gross</span>
                <span className="font-mono font-bold text-sm text-slate-900 dark:text-white">
                  ₹{formatRupeesToINR(record.internal_amount)}
                </span>
                <span className="text-[10px] text-slate-500 block mt-1">{record.internal_date}</span>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                <span className="text-[10px] text-slate-400 font-semibold uppercase block mb-1">Bank Settlement</span>
                <span className={`font-mono font-bold text-sm ${record.bank_amount === 0 ? 'text-red-500' : 'text-emerald-500'}`}>
                  ₹{formatRupeesToINR(record.bank_amount)}
                </span>
                <span className="text-[10px] text-slate-500 block mt-1">{record.bank_date}</span>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                <span className="text-[10px] text-slate-400 font-semibold uppercase block mb-1">Variance / Diff</span>
                <span className={`font-mono font-bold text-sm ${diffRupees > 0 ? 'text-amber-500' : 'text-slate-400'}`}>
                  ₹{formatRupeesToINR(diffRupees)}
                </span>
                <span className="text-[10px] text-slate-500 block mt-1">{record.payment_method}</span>
              </div>
            </div>

            {/* EXPLICIT GATEWAY MATH CARD (DIRECTIVE 2: RADICAL AUDIT TRANSPARENCY) */}
            <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 space-y-3">
              <div className="flex items-center justify-between">
                <h4 className="font-bold text-xs text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-1.5">
                  <Calculator className="w-4 h-4 text-blue-500" />
                  <span>Explicit Gateway Fee Math Breakdown</span>
                </h4>
                <span className="text-[10px] text-slate-500 font-mono">MDR: {math.mdrRatePct}% + 18% GST</span>
              </div>

              {/* Formula String Box */}
              <div className="p-2.5 rounded-lg bg-blue-500/10 border border-blue-500/20 text-xs font-mono font-bold text-blue-700 dark:text-blue-300">
                {math.formulaString}
              </div>

              {/* Visual Math Decomposition */}
              <div className="grid grid-cols-4 gap-2 text-center font-mono text-xs">
                <div className="p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                  <span className="text-[9px] text-slate-400 block uppercase font-sans">Ledger Gross</span>
                  <span className="font-bold text-slate-900 dark:text-white">
                    ₹{formatRupeesToINR(math.ledgerGrossRupees)}
                  </span>
                </div>
                <div className="p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                  <span className="text-[9px] text-amber-500 block uppercase font-sans">- {math.mdrRatePct}% MDR</span>
                  <span className="font-bold text-amber-600 dark:text-amber-400">
                    -₹{formatRupeesToINR(math.mdrRupees)}
                  </span>
                </div>
                <div className="p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                  <span className="text-[9px] text-purple-500 block uppercase font-sans">- 18% GST</span>
                  <span className="font-bold text-purple-600 dark:text-purple-400">
                    -₹{formatRupeesToINR(math.gstRupees)}
                  </span>
                </div>
                <div className="p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                  <span className="text-[9px] text-emerald-500 block uppercase font-sans">= Net Expected</span>
                  <span className="font-bold text-emerald-600 dark:text-emerald-400">
                    ₹{formatRupeesToINR(math.netExpectedRupees)}
                  </span>
                </div>
              </div>
            </div>

            {/* CANDIDATES EVALUATED COMPARISON TABLE */}
            {record.candidatesEvaluated && record.candidatesEvaluated.length > 0 && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h4 className="font-bold text-xs text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-1.5">
                    <Layers className="w-4 h-4 text-purple-500" />
                    <span>Candidate Matches Evaluated ({record.candidatesEvaluated.length})</span>
                  </h4>
                  <span className="text-[10px] text-slate-500 font-mono">Similarity & SLA Latency</span>
                </div>

                <div className="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden text-xs">
                  <table className="w-full text-left font-mono">
                    <thead className="bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400 text-[10px] uppercase">
                      <tr>
                        <th className="p-2.5">Candidate ID</th>
                        <th className="p-2.5">Amount</th>
                        <th className="p-2.5">Similarity</th>
                        <th className="p-2.5">Delay</th>
                        <th className="p-2.5">Outcome</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200 dark:divide-slate-800 bg-white dark:bg-slate-950">
                      {record.candidatesEvaluated.map((cand, idx) => (
                        <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-900/40">
                          <td className="p-2.5 font-bold text-slate-900 dark:text-white">
                            {cand.candidateId}
                          </td>
                          <td className="p-2.5 text-slate-700 dark:text-slate-300">
                            ₹{formatRupeesToINR(cand.bankAmount)}
                          </td>
                          <td className="p-2.5">
                            <span className={`px-1.5 py-0.5 rounded text-[10px] ${
                              cand.referenceSimilarityPct >= 90
                                ? 'bg-emerald-500/10 text-emerald-500'
                                : 'bg-amber-500/10 text-amber-500'
                            }`}>
                              {cand.referenceSimilarityPct}%
                            </span>
                          </td>
                          <td className="p-2.5 text-slate-500">
                            T+{cand.settlementDelayDays}d
                          </td>
                          <td className="p-2.5">
                            <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                              cand.evaluationOutcome === 'SELECTED'
                                ? 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400'
                                : cand.evaluationOutcome === 'COLLISION_AMBIGUOUS'
                                ? 'bg-rose-500/15 text-rose-600 dark:text-rose-400'
                                : 'bg-slate-500/15 text-slate-400'
                            }`}>
                              {cand.evaluationOutcome}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Detected Rule & Explanation */}
            <div className="space-y-2">
              <h4 className="font-bold text-xs text-slate-900 dark:text-white uppercase tracking-wider">
                Deterministic Policy & Audit Rationale
              </h4>
              <div className="p-4 rounded-xl bg-blue-50/50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-900/50 text-xs text-slate-800 dark:text-slate-200 leading-relaxed space-y-2">
                <div className="flex items-center space-x-2 text-blue-600 dark:text-blue-400 font-semibold">
                  <Cpu className="w-4 h-4" />
                  <span>Rule: {record.match_type}</span>
                </div>
                <p>{record.explanation}</p>
              </div>
            </div>

            {/* Manual Review Actions Section */}
            <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2 text-amber-600 dark:text-amber-400 font-bold text-xs">
                  <UserCheck className="w-4 h-4" />
                  <span>Controller Resolution Workflow</span>
                </div>
                <span className="text-[10px] text-slate-500 font-mono">Human-in-the-Loop</span>
              </div>

              <div className="grid grid-cols-3 gap-2">
                <div>
                  <label className="text-[10px] text-slate-400 block mb-1 font-semibold">Reviewer Name</label>
                  <input
                    type="text"
                    value={reviewerName}
                    onChange={(e) => setReviewerName(e.target.value)}
                    className="w-full px-3 py-1.5 text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-mono"
                  />
                </div>
                <div>
                  <label className="text-[10px] text-slate-400 block mb-1 font-semibold">Ops Escalation Email</label>
                  <input
                    type="email"
                    value={opsEmail}
                    onChange={(e) => setOpsEmail(e.target.value)}
                    className="w-full px-3 py-1.5 text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-mono"
                  />
                </div>
                <div>
                  <label className="text-[10px] text-slate-400 block mb-1 font-semibold">Audit Note (Optional)</label>
                  <input
                    type="text"
                    placeholder="e.g. Gateway fee adjustment"
                    value={note}
                    onChange={(e) => setNote(e.target.value)}
                    className="w-full px-3 py-1.5 text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-mono"
                  />
                </div>
              </div>

              {actionSuccessMsg && (
                <div className="p-2.5 rounded-lg bg-emerald-500/20 border border-emerald-500/40 text-emerald-600 dark:text-emerald-400 text-xs font-bold flex items-center space-x-2 animate-in fade-in duration-150">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 flex-shrink-0" />
                  <span>{actionSuccessMsg}</span>
                </div>
              )}

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-1">
                <button
                  onClick={() => handleAction('RESOLVE_MATCHED')}
                  disabled={isSubmitting}
                  className="flex items-center justify-center space-x-1.5 py-2 px-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow transition disabled:opacity-50"
                  title="Mark transaction as Matched / Resolved"
                >
                  <UserCheck className="w-3.5 h-3.5 flex-shrink-0" />
                  <span>Resolve: Matched</span>
                </button>
                <button
                  onClick={() => handleAction('RESOLVE_UNMATCHED')}
                  disabled={isSubmitting}
                  className="flex items-center justify-center space-x-1.5 py-2 px-2.5 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-bold text-xs shadow transition disabled:opacity-50"
                  title="Mark transaction as Not Matched / Confirmed Discrepancy"
                >
                  <UserX className="w-3.5 h-3.5 flex-shrink-0" />
                  <span>Resolve: Not Matched</span>
                </button>
                <button
                  onClick={() => handleAction('ESCALATE')}
                  disabled={isSubmitting}
                  className="flex items-center justify-center space-x-1.5 py-2 px-2.5 rounded-lg bg-amber-600 hover:bg-amber-500 text-white font-bold text-xs shadow transition disabled:opacity-50"
                  title="Escalate transaction to Ops via Email"
                >
                  <Mail className="w-3.5 h-3.5 flex-shrink-0" />
                  <span>Escalate to Ops</span>
                </button>
                <button
                  onClick={() => handleAction('OVERRIDE')}
                  disabled={isSubmitting}
                  className="flex items-center justify-center space-x-1.5 py-2 px-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow transition disabled:opacity-50"
                  title="Override AI Engine Rule as Matched"
                >
                  <Sparkles className="w-3.5 h-3.5 flex-shrink-0" />
                  <span>Override Rule</span>
                </button>
              </div>
            </div>

          </div>
        </div>

        {/* Footer info */}
        <div className="p-4 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900 text-xs text-slate-500 flex justify-between items-center">
          <span className="font-mono">Logged by Nexus Reconcile Policy Engine</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800 text-xs font-semibold"
          >
            Close Drawer
          </button>
        </div>

      </div>
    </div>
  );
};

